export default {
  printWidth: 152,
  singleQuote: true,
  trailingComma: 'all',
  importOrder: [
    '<TYPES>^[react]',
    '<TYPES>',
    '<TYPES>^[@]',
    '<BUILTIN_MODULES>',
    '^react$',
    '^next',
    '<THIRD_PARTY_MODULES>',
    '^[.]',
    '^(?!.*[.]css$)[./].*$',
    '.css$',
  ],
  importOrderTypeScriptVersion: '5.0.0',
  tailwindFunctions: ['cn'],
  plugins: [import('@ianvs/prettier-plugin-sort-imports'), import('prettier-plugin-tailwindcss')],
};
